name: Build the main branch and publish it to artifactory

on:
  push:
    branches: [ darren/change-name ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.6, 3.7, 3.8, 3.9 ]
    steps:
      - name: setup
        run: |
          export REPO="pyhocon"
          export PY_REPO_VERSION=$(REPO)_runner${{ matrix.python-version }}
          source /etc/profile && source /etc/sysdenv
          load-pyenv
          python -v; which python
          pyenv install ${{ matrix.python-version }} -s
          pyenv virtualenv $PY_REPO_VERSION && pyenv local $PY_REPO_VERSION
          PYENV_ROOT="/home/ec2-user/.pyenv/versions/$PY_REPO_VERSION"
          echo "$PYENV_ROOT/bin:/home/ec2-user/.local/bin:$PATH" >> $GITHUB_PATH
      - name: Pip Install Build Tools
        run: pip install --upgrade build twine
      - name: Build
        run: python -m build