name: Build the main branch and publish it to artifactory

on:
  push:
    branches: [ darren/test-centos ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.6, 3.7, 3.8, 3.9 ]
    steps:
      - name: setup
        run: |
          source /etc/profile && source /etc/sysdenv
          load-pyenv
          python -v; which python
          echo $PYENV_ROOT
          $PYENV_ROOT=$(pwd)
          echo $PYENV_ROOT
          pyenv install ${{ matrix.python-version }} -s
          pyenv virtualenv runner${{ matrix.python-version }} && pyenv local runner${{ matrix.python-version }}
          python_location="$PYENV_ROOT/runner${{ matrix.python-version }}"
          echo "python_location/bin:/home/ec2-user/.local/bin:$PATH" >> $GITHUB_PATH
      - name: Pip Install Build Tools
        run: pip install --upgrade build twine
      - name: Build
        run: python -m build